apiVersion: v1
kind: Service
metadata:
  name: holodeck-b2b
  labels:
    app.kubernetes.io/name: holodeck-b2b
spec:
  selector:
    app.kubernetes.io/name: holodeck-b2b
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
